---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: c1
  namespace: c1
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: DockerCluster
    name: c1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DockerCluster
metadata:
  name: c1
  namespace: c1
